services:
  db:
    image: postgres:15-alpine
    container_name: graphql_auth_db_container
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: graphql_auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
